language: python
python:
  - '2.6'
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt
install:
  - pip install ansible==1.9.1
script:
  - cd test/integration && ansible-playbook -i inventory playbook.yml --connection=local --sudo
