language: python
python:
  - '2.6'
  - pypy
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt
install:
  - pip install ansible==1.9.1
script:
  - ansible-playbook -i test/integration/inventory test/integration/playbook.yml --connection=local --sudo
